import { useEffect, useRef, useState } from 'react';
import { Apple, Camera, ChevronRight, ImagePlus, Loader2, Save, ScanLine, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { authenticatedApiPost } from '../lib/api';

const allowed = new Set(['image/jpeg', 'image/png', 'image/webp']);
export default function NutritionExperience() {
  const { user } = useAuth();
  const fileInput = useRef(null); const [image, setImage] = useState(null); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [journal, setJournal] = useState([]);
  const journalKey = user?.id ? `wtp_meal_journal_v1_${user.id}` : null;
  useEffect(() => {
    if (!journalKey) return undefined;
    let active = true;
    queueMicrotask(() => {
      if (!active) return;
      try { setJournal(JSON.parse(localStorage.getItem(journalKey) || '[]').slice(0, 12)); } catch { setJournal([]); }
    });
    return () => { active = false; };
  }, [journalKey]);
  const choose = async (file) => { setError(''); setResult(null); if (!file) return; if (!allowed.has(file.type) || file.size > 3.5 * 1024 * 1024) { setError('Choose a JPEG, PNG, or WebP photo under 3.5 MB.'); return; } const dataUrl = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); setImage(dataUrl); };
  const analyze = async () => { if (!image || loading) return; setLoading(true); setError(''); try { const data = await authenticatedApiPost('/api/parse-food', { imageUri: image }); setResult(data.macros); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Food Scanner is unavailable.'); } finally { setLoading(false); } };
  const saveToJournal = () => { if (!result || !journalKey) return; const item = { id: crypto.randomUUID(), savedAt: new Date().toISOString(), foods: result.detectedFoods || [], calories: result.caloriesRange || '—', confidence: result.confidence || 'Unknown' }; const next = [item, ...journal].slice(0, 12); setJournal(next); try { localStorage.setItem(journalKey, JSON.stringify(next)); } catch { setError('This scan could not be saved to the device journal.'); } };
  const scanState = loading ? 'is-scanning' : result ? 'has-result' : image ? 'is-ready' : 'is-idle';
  return <div className="experience nutrition-experience"><section className="nutrition-hero"><p className="eyebrow">AI nutritionist</p><h1>Point.<br />Scan. Understand.</h1><p>Food photos are estimates—not measurements. Every result shows a range and its assumptions.</p></section><section className="nutrition-overview"><Link to="/nutritionist"><Apple size={18} /><span><strong>Talk to your nutritionist</strong><small>Ask real authenticated AI guidance about meals, timing, and macros.</small></span><ChevronRight size={18} /></Link><div><span>Device meal journal</span><strong>{journal.length}</strong><small>saved analyses</small></div></section><section className={`scanner-stage ${image ? 'has-image' : ''} ${scanState}`}><div className="scanner-lens">{image ? <img src={image} alt="Selected meal" /> : <div className="scanner-empty"><span className="scanner-reticle"><ScanLine size={33} /></span><h2>Your next meal, in context.</h2><p>Select a photo for an authenticated visual estimate.</p></div>}<span className="scan-corner top-left" /><span className="scan-corner top-right" /><span className="scan-corner bottom-left" /><span className="scan-corner bottom-right" />{loading && <><span className="scan-beam" /><div className="scan-processing"><Loader2 className="animate-spin" size={16} /> Reading the plate…</div></>}</div>{image && <button type="button" className="scan-remove" onClick={() => { setImage(null); setResult(null); }} aria-label="Remove selected meal photo"><X size={18} /></button>}</section><div className="scan-actions"><button type="button" className="secondary-action" onClick={() => fileInput.current?.click()}><ImagePlus size={17} /> {image ? 'Choose another photo' : 'Choose meal photo'}</button><button type="button" className="primary-action" disabled={!image || loading} onClick={analyze}>{loading ? <Loader2 className="animate-spin" size={17} /> : <Camera size={17} />}{loading ? 'Analyzing…' : 'Scan meal'}</button></div><p className="scanner-disclosure">Visual estimates can be wrong. Review portions and assumptions before using them.</p><Link to="/nutritionist" className="nutrition-coach-link">Need help interpreting this? <span>Ask Nutritionist</span></Link><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={(event) => choose(event.target.files?.[0])} />{error && <div className="inline-state is-error">{error}</div>}{result && <FoodResult result={result} save={saveToJournal} />}{journal.length > 0 && <section className="meal-journal"><div className="section-heading"><div><p className="eyebrow">Meal journal</p><h2>Saved on this device</h2></div></div>{journal.map((entry) => <article key={entry.id}><span>{new Date(entry.savedAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</span><div><strong>{entry.foods.join(', ') || 'Meal analysis'}</strong><small>{entry.calories} kcal · {entry.confidence} confidence</small></div></article>)}</section>}</div>;
}
function FoodResult({ result, save }) { const macros = [['Calories', result.caloriesRange, 'kcal'], ['Protein', result.proteinRange, 'g'], ['Carbs', result.carbsRange, 'g'], ['Fat', result.fatRange, 'g']]; return <section className="food-result"><div className="food-result-head"><div><p className="eyebrow">Visual estimate</p><h2>{result.detectedFoods?.join(', ') || 'Meal analysis'}</h2></div><span className={`confidence ${String(result.confidence || '').toLowerCase()}`}>{result.confidence || 'Unknown'} confidence</span></div><div className="macro-grid">{macros.map(([label, value, unit]) => <div key={label}><span>{label}</span><strong>{value}<small> {unit}</small></strong></div>)}</div>{result.assumptions?.length ? <div className="assumptions"><strong>Assumptions</strong><p>{result.assumptions.join(' · ')}</p></div> : null}{result.followUpQuestion ? <div className="follow-up"><ScanLine size={16} /><span>{result.followUpQuestion}</span></div> : null}<button type="button" className="save-meal-analysis" onClick={save}><Save size={15} /> Save analysis on this device</button></section>; }
