import { useRef, useState } from 'react';
import { Camera, ImagePlus, Loader2, ScanLine, X } from 'lucide-react';
import { authenticatedApiPost } from '../lib/api';

const allowed = new Set(['image/jpeg', 'image/png', 'image/webp']);
export default function NutritionExperience() {
  const fileInput = useRef(null); const [image, setImage] = useState(null); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const choose = async (file) => { setError(''); setResult(null); if (!file) return; if (!allowed.has(file.type) || file.size > 3.5 * 1024 * 1024) { setError('Choose a JPEG, PNG, or WebP photo under 3.5 MB.'); return; } const dataUrl = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); setImage(dataUrl); };
  const analyze = async () => { if (!image || loading) return; setLoading(true); setError(''); try { const data = await authenticatedApiPost('/api/parse-food', { imageUri: image }); setResult(data.macros); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Food Scanner is unavailable.'); } finally { setLoading(false); } };
  return <div className="experience nutrition-experience"><section className="nutrition-hero"><p className="eyebrow">AI nutritionist</p><h1>Point.<br />Scan. Understand.</h1><p>Food photos are estimates—not measurements. Every result shows a range and its assumptions.</p></section><section className={`scanner-stage ${image ? 'has-image' : ''}`}>{image ? <img src={image} alt="Selected meal" /> : <div className="scanner-empty"><span className="scanner-reticle"><ScanLine size={33} /></span><h2>Your next meal, in context.</h2><p>Select a photo for an authenticated visual estimate.</p></div>}{image && <button type="button" className="scan-remove" onClick={() => { setImage(null); setResult(null); }}><X size={18} /></button>}</section><div className="scan-actions"><button type="button" className="secondary-action" onClick={() => fileInput.current?.click()}><ImagePlus size={17} /> {image ? 'Choose another photo' : 'Choose meal photo'}</button><button type="button" className="primary-action" disabled={!image || loading} onClick={analyze}>{loading ? <Loader2 className="animate-spin" size={17} /> : <Camera size={17} />}{loading ? 'Analyzing…' : 'Scan meal'}</button></div><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={(event) => choose(event.target.files?.[0])} />{error && <div className="inline-state is-error">{error}</div>}{result && <FoodResult result={result} />}</div>;
}
function FoodResult({ result }) { const macros = [['Calories', result.caloriesRange, 'kcal'], ['Protein', result.proteinRange, 'g'], ['Carbs', result.carbsRange, 'g'], ['Fat', result.fatRange, 'g']]; return <section className="food-result"><div className="food-result-head"><div><p className="eyebrow">Visual estimate</p><h2>{result.detectedFoods?.join(', ') || 'Meal analysis'}</h2></div><span className={`confidence ${String(result.confidence || '').toLowerCase()}`}>{result.confidence || 'Unknown'} confidence</span></div><div className="macro-grid">{macros.map(([label, value, unit]) => <div key={label}><span>{label}</span><strong>{value}<small> {unit}</small></strong></div>)}</div>{result.assumptions?.length ? <div className="assumptions"><strong>Assumptions</strong><p>{result.assumptions.join(' · ')}</p></div> : null}{result.followUpQuestion ? <div className="follow-up"><ScanLine size={16} /><span>{result.followUpQuestion}</span></div> : null}</section>; }
